Unloading the cpe module is insufficient to restore the system defaults.
Please run 'source
/opt/cray/pe/cpe/24.07/restore_lmod_system_defaults.[csh|sh]'. 
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: /opt/cray/pe/lmod/modulefiles/mpi/gnu/12.0/ofi/1.0/cray-mpich/8.0
================================================================================
BUILDING
smyle
smyle.cdr-atlas-v0.glb-erw_North_Atlantic_basin_030_1999-10-01_00123.001
{"cdr_forcing": "ERW", "cdr_forcing_file": "/global/cfs/projectdirs/m4746/Projects/OAE-Efficiency-Map/data/alk-forcing/OAE-Efficiency-Map/alk-forcing-North_Atlantic_basin.030-1999-10.nc", "refdate": "0347-10-01", "stop_n": 15, "wallclock": "10:00:00", "curtail_output": true, "queue": "regular"}
================================================================================

Traceback (most recent call last):
  File "/global/u2/m/mattlong/codes/Ocean-CDR-Atlas-v0/workflows/atlas.py", line 949, in <module>
    main()
  File "/global/homes/m/mattlong/.conda/envs/cworthy/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/m/mattlong/.conda/envs/cworthy/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/global/homes/m/mattlong/.conda/envs/cworthy/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/m/mattlong/.conda/envs/cworthy/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u2/m/mattlong/codes/Ocean-CDR-Atlas-v0/workflows/atlas.py", line 945, in main
    gen_case(case, clobber=clobber, **kwargs)
  File "/global/u2/m/mattlong/codes/Ocean-CDR-Atlas-v0/workflows/cesm.py", line 40, in create_smyle_clone
    not os.path.exists(caseroot) or clobber
AssertionError: Case smyle.cdr-atlas-v0.glb-erw_North_Atlantic_basin_030_1999-10-01_00123.001 exists; caseroot:
/global/cfs/projectdirs/m4746/Projects/Ocean-CDR-Atlas-v0/cases/smyle.cdr-atlas-v0.glb-erw_North_Atlantic_basin_030_1999-10-01_00123.001

